services:
  api-gateway:
    build: ./services/api-gateway
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - AUTH_SERVICE_URL=http://auth-service:3001
      - BLOG_SERVICE_URL=http://blog-service:3002
      - COMMENT_SERVICE_URL=http://comment-service:3003
      - PROFILE_SERVICE_URL=http://profile-service:3004
    depends_on:
      - auth-service
      - blog-service
      - comment-service
      - profile-service
    networks:
      - microservices-network

  auth-service:
    build: ./services/auth-service
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://mongodb:27017/auth
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - microservices-network

  blog-service:
    build: ./services/blog-service
    environment:
      - PORT=3002
      - MONGO_URI=mongodb://mongodb:27017/blog
      - AUTH_SERVICE_URL=http://auth-service:3001
    depends_on:
      mongodb:
        condition: service_healthy
      auth-service:
        condition: service_started
    networks:
      - microservices-network

  comment-service:
    build: ./services/comment-service
    environment:
      - PORT=3003
      - MONGO_URI=mongodb://mongodb:27017/comment
      - AUTH_SERVICE_URL=http://auth-service:3001
    depends_on:
      mongodb:
        condition: service_healthy
      auth-service:
        condition: service_started
    networks:
      - microservices-network

  profile-service:
    build: ./services/profile-service
    environment:
      - PORT=3004
      - MONGO_URI=mongodb://mongodb:27017/profile
      - AUTH_SERVICE_URL=http://auth-service:3001
    depends_on:
      mongodb:
        condition: service_healthy
      auth-service:
        condition: service_started
    networks:
      - microservices-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      - MONGO_INITDB_DATABASE=admin

volumes:
  mongodb_data:

networks:
  microservices-network:
    driver: bridge